conversation/urls.py
from django.urls import path
from . import views

app_name = "conversation"

urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('',views.inbox,name='inbox'),
    # for finding detail of each inbox message
    path('<int:pk>',views.detail,name="detail")

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('',views.index,name='index')
]

item/urls.py
from django.urls import path
from . import views
#this will help us for cross movement between the apps because just the name won't be enough to 
# differentiate in html hyper links
app_name = 'item'
urlpatterns = [
    path('<int:pk>',view=views.detail,name='detail'),
    
    path('new/',view=views.new,name='new'),
    path('<int:pk>/delete/',view=views.delete,name='delete'),
     path('<int:pk>/edit/',view=views.edit,name='edit'),
     path('',views.items,name='items')

]

pmp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pmpapp.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls'))
]
if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pmpapp/urls.py
from django.urls import path

# for authentication for user login we will import views from django auth
from django.contrib.auth import views as auth_views
from . import views
from .import forms

app_name = 'pmpapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    # in this code we will use django authentication but will tell them to use on which form which 
    #in this case is our login form
    path('login/',auth_views.LoginView.as_view(template_name = 'login.html',authentication_form = forms.LoginForm),name="login")
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 255)
    class Meta:
        ordering = ('name',)
    def __str__(self)    :
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category,related_name = 'items',on_delete = models.CASCADE)
    name = models.CharField(max_length = 255)
    description = models.TextField(blank = True,null = True)
    price = models.FloatField()
    image = models.ImageField(upload_to="img/%y",blank=True,null=True)
    #we will use this to display only those itmes that are not sold, means helps us in filtering
    is_sold = models.BooleanField(default = False)
    created_by = models.ForeignKey(User,related_name = 'items',on_delete = models.CASCADE)
    created_at = models.DateField(auto_now_add = True)
    def __str__(self)    :
        return self.name

item/forms.py
from django import forms
from .models import Item


INPUT_CLASSES = "bg-black"

class newItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = {'category','name','description','price','image'}

        widgets = {
            'category':forms.Select(attrs={
                'class':INPUT_CLASSES
            }),
             'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
             'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES
            }),
             'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),

            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),

        }

        # write this code to edit the item
class editItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = {'name','description','price','image','is_sold'}

        widgets = {
            
             'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
             'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES
            }),
             'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),

            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),

        }        

item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Category,Item
#add this so login will be require to use certain view function
from django.contrib.auth.decorators import login_required
from .forms import newItemForm,editItemForm
# import this to allow you to search even with different fields like description
from django.db.models import Q
# Create your views here.

def detail(request,pk):
    item = get_object_or_404(Item,pk= pk)
    # to show related objects of the same category and we use [0:3] to display three items at a time
    related_items = Item.objects.filter(category = item.category,is_sold = False).exclude(pk = pk)[0:3]
    return render(request,'detail.html',{'item':item,'related_items':related_items})

@login_required
def new(request):
    if request.method == 'POST':
        form = newItemForm(request.POST,request.FILES)

        if form.is_valid:
            #since we are going to store an image as well we fist save the formn and then save database
            item = form.save(commit= False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail',pk = item.id)
    else:
        form = newItemForm()
    return render(request,'form.html',{'form':form,'title':'new Item'})

@login_required
def edit(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by = request.user)
    if request.method == 'POST':
        form = editItemForm(request.POST,request.FILES,instance=item)

        if form.is_valid():
            #since we are editing the form so form is already saved so no need to write extra code as we did
            # for new method
            item.save()
            return redirect('item:detail',pk = item.id)
    else:
        # the reason we write instace is if we don't we will only see an empty form so we fill it with existing 
        # or old form data
        form = editItemForm(instance=item)
    return render(request,'form.html',{'form':form,'title':'edit Item'})

@login_required
def delete(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by = request.user)
    item.delete()

    return redirect('dashboard:index')

# add this code to allow you to search items in the market place
def items(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category',0)
    items = Item.objects.filter(is_sold = False)
    categories = Category.objects.all()
    # if category is clicked
    if category_id:
        items = items.filter(category_id = category_id)

    if query:
        items = items.filter(Q(name__icontains=query )| Q(description__icontains = query))
    
    return render(request,'items.html',{"items":items,"query":query,"categories":categories,'category_id':int(category_id)})

item/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}  | Puddle</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url "pmpapp:index" %}">Home</a>
              <a class="nav-link" href="#">New Item</a>
              <a class="nav-link" href="#">Browse</a>
              {% comment %} write this code to apply a login that if user exists then allow it to go forward {% endcomment %}
              {% if request.user.is_authenticated %}
              <a class="nav-link active" aria-current="page" href="{% url "conversation:inbox" %}">Inbox</a>
              <a class="nav-link active" aria-current="page" href="{% url "dashboard:index" %}">Dashboard</a>
              <a class="nav-link active" aria-current="page" href="{% url "item:new" %}">Add Item</a>
              {% else %}
              <a class="nav-link active" aria-current="page" href="{% url "pmpapp:signup" %}">SignUp</a>
              <a class="nav-link active" aria-current="page" href="{% url "pmpapp:login" %}">Login</a>
              {% endif %}
            
            </div>
          </div>
        </div>
      </nav>
</header>
<body>
    
    {% block content %}
    {% endblock content %}
</body>

<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">
    <!-- Footer -->
    <footer class="text-center text-white" style="background-color: #3f51b5">
      <!-- Grid container -->
      <div class="container">
        <!-- Section: Links -->
        <section class="mt-5">
          <!-- Grid row-->
          <div class="row text-center d-flex justify-content-center pt-5">
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">About us</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">Products</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">Awards</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">Help</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="{% url "pmpapp:contact" %}" class="text-white">Contact</a>
              </h6>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row-->
        </section>
        <!-- Section: Links -->
  
        <hr class="my-5" />
  
        <!-- Section: Text -->
        <section class="mb-5">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
                distinctio earum repellat quaerat voluptatibus placeat nam,
                commodi optio pariatur est quia magnam eum harum corrupti
                dicta, aliquam sequi voluptate quas.
                Hello How are you 
              </p>
            </div>
          </div>
        </section>
        <!-- Section: Text -->
  
        <!-- Section: Social -->
        <section class="text-center mb-5">
          <a href="" class="text-white me-4">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-github"></i>
          </a>
        </section>
        <!-- Section: Social -->
      </div>
      <!-- Grid container -->
  
      <!-- Copyright -->
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/"
           >MDBootstrap.com</a
          >
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  </div>
  <!-- End of .container -->

</html>

item/templates/detail.html
{% extends "base.html" %}
{% block title %} {{item.name}}{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <img src="{{item.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{item.name}}e</h5>
          <p class="card-text">{{item.description}}</p>
          <p class="card-text">Price: Rs{{item.price}}</p>
          <a href="#" class="btn btn-primary">Add to Cart</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h4>Item Details</h4>
      <ul>
        <li>Detail 1: Some details about the item.</li>
        <li>Detail 2: Additional information about the item.</li>
        <li>Detail 3: More specifications about the item.</li>
        <li>Detail 4: Any other relevant information.</li>
      </ul>
      <div class="d-grid" style="align-items: center; align-self: center;">
        {% comment %} write this code when you want to display Delete and Edit option based
        on the user authentication, if it is seller display option to delete or edit it {% endcomment %}
        {% if request.user == item.created_by %}
        <div>

          <p> this is your item<p>
            <a class="nav-link active" aria-current="page" href="{% url 'item:delete' pk=item.pk %}">Delete Item</a>
            <a class="nav-link active" aria-current="page" href="{% url 'item:edit' pk=item.id %}">Edit Item</a>

        </div>
        {% else %}
        <button type="button" style="width: 50%; align-self:center;" class="btn btn-primary btn-block">
          <a href="{% url 'conversation:new' item.id %}"> Contact Seller</a>
        </button>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<h2>Related Items</h2>
{% for item in related_items %}
<div>
    <div class="card-rows">
        <div class="col-md-3 mb-4">
          <a href="{% url "item:detail" item.id %}">
            <div class="card">
              <img class="card-img-top" src="{{item.image.url}}" width="100" height="200" alt="Card image">
              <div class="card-body">
                <h4 class="card-title">{{item.name}}</h4>
                <p class="card-text">{{item.description}}</p>
               
                
              </div>
            </div>
          </a>
        </div>
</div>
{% endfor %}
{% endblock content %}

item/templates/form.html
{% extends "base.html" %}
{% block title %} {{title}}{% endblock title %} 
{% block content %}

<h1>{{title}}</h1>
<form method="post" action="." enctype="multipart/form-data">
    {%csrf_token%}
    <div>
        {{form.as_p}}

    </div>
    
    {% if form.errors or form.non_field_errors %}
    <div>
{% for field in form %}
{{field.errors}}
{% endfor %}
{{form.non_field_errors}}
    </div>
    
    {% endif %}

    
    <button>Submit</button>
</form>


{% endblock content %}

item/templates/items.html
{% extends "base.html" %}

{% block title %}Searching Item{% endblock title %}

{% block content %}
<div class = 'parentFlex'>


    <form method = "get" action="{% url "item:items" %}">
       <input type="text" name="query" value="{{query}}"placeholder = "find a bike or a car">
       <button>Search</button>
    </form>
<p>Categories</p>
<ul>
    {% for category in categories %}
    
    <li {% if category.id == category_id %}{% endif %}>
        <a href="{% url "item:items" %}?query={{query}}&category={{category.id}}">{{category.name}}</a>
    </li>
    
    
    {% endfor %}
    <ul>
      <li>
        <a href="{% url "item:items" %}">Clear Filter</a>
      </li>
    </ul>
</ul>
</div>
<div class="container-fluid p-3 my-3 bg-dark text-white">
  
    {% for item in items %}
    <div>
        <div class="card-rows">
            <div class="col-md-3 mb-4">
              <a href="{% url "item:detail" item.id %}">
                <div class="card">
                  <img class="card-img-top" src="{{item.image.url}}" width="100" height="200" alt="Card image">
                  <div class="card-body">
                    <h4 class="card-title">{{item.name}}</h4>
                    <p class="card-text">{{item.description}}</p>
                   
                    
                  </div>
                </div>
              </a>
            </div>
    </div>
    {% endfor %}
    
    
    </div>  

{% endblock content %}