dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('',views.index,name='index')
]

item/urls.py
from django.urls import path
from . import views
#this will help us for cross movement between the apps because just the name won't be enough to 
# differentiate in html hyper links
app_name = 'item'
urlpatterns = [
    path('<int:pk>',view=views.detail,name='detail'),
    
    path('new/',view=views.new,name='new'),
    path('<int:pk>/delete/',view=views.delete,name='delete'),
     path('<int:pk>/edit/',view=views.edit,name='edit'),
     path('',views.items,name='items')

]

pmp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pmpapp.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls'))
]
if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pmpapp/urls.py
from django.urls import path

# for authentication for user login we will import views from django auth
from django.contrib.auth import views as auth_views
from . import views
from .import forms

app_name = 'pmpapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    # in this code we will use django authentication but will tell them to use on which form which 
    #in this case is our login form
    path('login/',auth_views.LoginView.as_view(template_name = 'login.html',authentication_form = forms.LoginForm),name="login")
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from item.models import Item
# Create your views here.

#we use login required to first let user log in and then access the data
@login_required
def index(request):
    #this is power of django, where you don't need to create a separate funtion to filter items based on user pk
    #let django handle it
    items = Item.objects.filter(created_by = request.user)
    return render(request,'dashboard.html',{'items':items})

dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}  | Puddle</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url "pmpapp:index" %}">Home</a>
              <a class="nav-link" href="#">New Item</a>
              <a class="nav-link" href="#">Browse</a>
              {% comment %} write this code to apply a login that if user exists then allow it to go forward {% endcomment %}
              {% if request.user.is_authenticated %}
              <a class="nav-link active" aria-current="page" href="#">Inbox</a>
              <a class="nav-link active" aria-current="page" href="{% url "dashboard:index" %}">Dashboard</a>
              <a class="nav-link active" aria-current="page" href="{% url "item:new" %}">Add Item</a>
              {% else %}
              <a class="nav-link active" aria-current="page" href="{% url "pmpapp:signup" %}">SignUp</a>
              <a class="nav-link active" aria-current="page" href="{% url "pmpapp:login" %}">Login</a>
              {% endif %}
            
            </div>
          </div>
        </div>
      </nav>
</header>
<body>
    
    {% block content %}
    {% endblock content %}
</body>

<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">
    <!-- Footer -->
    <footer class="text-center text-white" style="background-color: #3f51b5">
      <!-- Grid container -->
      <div class="container">
        <!-- Section: Links -->
        <section class="mt-5">
          <!-- Grid row-->
          <div class="row text-center d-flex justify-content-center pt-5">
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">About us</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">Products</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">Awards</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="#!" class="text-white">Help</a>
              </h6>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href="{% url "pmpapp:contact" %}" class="text-white">Contact</a>
              </h6>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row-->
        </section>
        <!-- Section: Links -->
  
        <hr class="my-5" />
  
        <!-- Section: Text -->
        <section class="mb-5">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
                distinctio earum repellat quaerat voluptatibus placeat nam,
                commodi optio pariatur est quia magnam eum harum corrupti
                dicta, aliquam sequi voluptate quas.
              </p>
            </div>
          </div>
        </section>
        <!-- Section: Text -->
  
        <!-- Section: Social -->
        <section class="text-center mb-5">
          <a href="" class="text-white me-4">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-github"></i>
          </a>
        </section>
        <!-- Section: Social -->
      </div>
      <!-- Grid container -->
  
      <!-- Copyright -->
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/"
           >MDBootstrap.com</a
          >
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  </div>
  <!-- End of .container -->

</html>

dashboard/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock title %}
{% block content %}

<h2>My Items</h2>

<div class="container-fluid p-3 my-3 bg-dark text-white">
  
    {% for item in items %}
    <div>
        <div class="card-rows">
            <div class="col-md-3 mb-4">
              <a href="{% url "item:detail" item.id %}">
                <div class="card">
                  <img class="card-img-top" src="{{item.image.url}}" width="100" height="200" alt="Card image">
                  <div class="card-body">
                    <h4 class="card-title">{{item.name}}</h4>
                    <p class="card-text">{{item.description}}</p>
                   
                    
                  </div>
                </div>
              </a>
            </div>
    </div>
    {% endfor %}
    <h1 style="text-align: center;">Categories</h1>
    <div class="card-columns" style="align-items: center;">
    {% for categories in category %}
        <div class="card bg-primary" style="align-items: center;">
          <div class="card-body text-center" style="align-items: center;">
            <h1 class="card-text">{{categories.name}}</h1>
            <p class="card-text">{{categories.items.count}} items</p>
          </div>
        </div>
 
      {% endfor %}
    
    </div>  

{% endblock content %}